owner: Whipcode-API
repo: upptime

sites:
  - name: Whipcode API
    url: $WHIPCODE_BACKEND
    method: POST
  - name: Whipcode Site
    url: https://whipcode.app
  - name: RapidAPI Proxy
    url: https://rapidapi.com

status-website:
  cname: status.whipcode.app
  name: Status | Whipcode
  themeUrl: https://av9.dev/whipcode/assets/status.css
  favicon: https://av9.dev/whipcode/assets/favicon.png
