owner: Whipcode-API
repo: upptime

sites:
  - name: Whipcode API
    url: $WHIPCODE_BACKEND
    method: POST
    icon: https://icons.duckduckgo.com/ip3/null.ico
  - name: Whipcode Site
    url: https://whipcode.app
    icon: https://icons.duckduckgo.com/ip3/null.ico
  - name: RapidAPI Proxy
    url: https://whipcode.p.rapidapi.com
    method: POST
    expectedStatusCodes:
      - 200
      - 201
      - 401
    icon: https://icons.duckduckgo.com/ip3/null.ico

status-website:
  introTitle: "**Uptime Monitor**"
  introMessage: "[<- Home](https://whipcode.app)"
  cname: status.whipcode.app
  name: Status | Whipcode
  themeUrl: https://av9.dev/whipcode/assets/status.css
  favicon: https://av9.dev/whipcode/assets/favicon.png
  links:
    - rel: stylesheet
      href: https://av9.dev/whipcode/assets/custom.css

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

i18n:
  footer: ""
